# Generated by Django 3.0.8 on 2020-07-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='continent',
            new_name='country',
        ),
    ]
